  - name: Install MySQL Server
    apt: name={{ item }}
    with_items:
      - python-mysqldb
      - mysql-server

  - name: Start the MySQL service
    action: service name=mysql state=started

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
  - name: update mysql root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: copy .my.cnf file with root password credentials
    template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600